#!/usr/bin/env bash
	find . \
			-type f \( \
			-name '*.ts' -o \
			-name '*.js' -o \
			-name '*.json' -o \
			-name '*.md' -o \
			-name '*.yml' \) | \
		grep -v node_modules | \
		grep -v '^\./bot/dist/' | \
		grep -v '^\./docs/.*\.js$' | \
		grep -v '^\./website/website/' | \
		xargs $(dirname $0)/node_modules/.bin/prettier "$@"
